url: https://tarkiz.biz
baseurl: 

# Site settings
title: Tarkiz.Biz Official Web
email: admin@tarkiz.biz
description: "Tarkiz Official Web represents Team Tarkiz, their ideas, projects and output."


# Team names, titles and social links
people:
- name: Muhammad Isrofan
  pic: 1
  position: Partner / Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Beta Uliansyah
  pic: 2
  position: Partner / System Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

#- name: Dzakwan Robbani
#  pic: 3
#  position: Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
